FROM phusion/passenger-ruby27:1.0.12

# Installation path
ENV HOME=/pact_broker
WORKDIR $HOME

RUN bash -lc 'rvm --default use ruby-2.4.5'

RUN bundler -v
RUN gem install --no-document --minimal-deps bundler -v 2.1.4
COPY pact_broker/Gemfile pact_broker/Gemfile.lock $HOME/
RUN bundle install --no-cache
